// Mock data for rooms
export const roomsData = [
  {
    id: 1,
    name: "Deluxe Ocean Suite",
    description: "Spacious luxury with premium amenities and stunning views",
    fullDescription:
      "Spacious suite with separate living area, premium furnishings, and stunning ocean views. Includes exclusive lounge access and personalized concierge service.",
    price: 349,
    image:
      "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80",
    guests: 2,
    bed: "King bed",
    view: "Ocean view",
    sqft: 520,
    floor: "Ground Floor",
    roomNumber: "A01",
    highlights: [
      { icon: "wifi", label: "Premium WiFi" },
      { icon: "coffee", label: "Espresso machine" },
      { icon: "tv", label: '65" Smart TV' },
      { icon: "wind", label: "Smart climate" },
      { icon: "bathtub", label: "Soaking tub" },
      { icon: "bar", label: "Premium bar" },
    ],
  },
  {
    id: 2,
    name: "Presidential Suite",
    description: "Ultimate luxury with private terrace and premium services",
    fullDescription:
      "Our most exclusive suite featuring separate living and dining areas, private terrace with panoramic views, and 24/7 butler service.",
    price: 899,
    image:
      "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800&q=80",
    guests: 4,
    bed: "King bed",
    view: "Panoramic view",
    sqft: 850,
    floor: "First Floor",
    roomNumber: "B01",
    highlights: [
      { icon: "wifi", label: "Premium WiFi" },
      { icon: "coffee", label: "Espresso machine" },
      { icon: "tv", label: '75" Smart TV' },
      { icon: "wind", label: "Smart climate" },
      { icon: "bathtub", label: "Soaking tub" },
      { icon: "bar", label: "Premium bar" },
    ],
  },
  {
    id: 3,
    name: "Garden Villa",
    description: "Private villa surrounded by tropical gardens",
    fullDescription:
      "Detached villa with private garden, outdoor seating area, and direct access to resort grounds. Perfect for those seeking tranquility.",
    price: 549,
    image:
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&q=80",
    guests: 3,
    bed: "Queen bed",
    view: "Garden view",
    sqft: 620,
    floor: "Ground Floor",
    roomNumber: "A02",
    highlights: [
      { icon: "wifi", label: "Premium WiFi" },
      { icon: "coffee", label: "Coffee maker" },
      { icon: "tv", label: '55" Smart TV' },
      { icon: "wind", label: "Smart climate" },
      { icon: "bathtub", label: "Rain shower" },
      { icon: "bar", label: "Mini bar" },
    ],
  },
  {
    id: 4,
    name: "Penthouse Suite",
    description: "Exclusive top-floor suite with city skyline views",
    fullDescription:
      "Top-floor luxury suite with floor-to-ceiling windows, private rooftop terrace, and stunning city skyline views. Features modern design with premium amenities.",
    price: 799,
    image:
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80",
    guests: 4,
    bed: "King bed",
    view: "City view",
    sqft: 750,
    floor: "Second Floor",
    roomNumber: "C01",
    highlights: [
      { icon: "wifi", label: "Premium WiFi" },
      { icon: "coffee", label: "Espresso machine" },
      { icon: "tv", label: '70" Smart TV' },
      { icon: "wind", label: "Smart climate" },
      { icon: "bathtub", label: "Soaking tub" },
      { icon: "bar", label: "Premium bar" },
    ],
  },
  {
    id: 5,
    name: "Executive Suite",
    description: "Modern comfort with workspace and business amenities",
    fullDescription:
      "Perfect for business travelers with dedicated workspace, high-speed internet, and premium office amenities alongside luxury accommodations.",
    price: 449,
    image:
      "https://images.unsplash.com/photo-1591088398332-8a7791972843?w=800&q=80",
    guests: 2,
    bed: "King bed",
    view: "City view",
    sqft: 480,
    floor: "First Floor",
    roomNumber: "B02",
    highlights: [
      { icon: "wifi", label: "Business WiFi" },
      { icon: "coffee", label: "Espresso machine" },
      { icon: "tv", label: '65" Smart TV' },
      { icon: "wind", label: "Smart climate" },
      { icon: "bathtub", label: "Walk-in shower" },
      { icon: "bar", label: "Mini bar" },
    ],
  },
  {
    id: 6,
    name: "Beachfront Villa",
    description: "Direct beach access with private pool and cabana",
    fullDescription:
      "Exclusive beachfront villa with private infinity pool, outdoor dining area, and direct beach access. Includes private cabana service.",
    price: 699,
    image:
      "https://images.unsplash.com/photo-1602002418082-a4443e081dd1?w=800&q=80",
    guests: 4,
    bed: "2 Queen beds",
    view: "Beach view",
    sqft: 920,
    floor: "Ground Floor",
    roomNumber: "A03",
    highlights: [
      { icon: "wifi", label: "Premium WiFi" },
      { icon: "coffee", label: "Espresso machine" },
      { icon: "tv", label: '65" Smart TV' },
      { icon: "wind", label: "Smart climate" },
      { icon: "bathtub", label: "Outdoor shower" },
      { icon: "bar", label: "Premium bar" },
    ],
  },
  {
    id: 7,
    name: "Mountain View Suite",
    description: "Serene retreat with breathtaking mountain vistas",
    fullDescription:
      "Peaceful suite with panoramic mountain views, private balcony, and cozy fireplace. Perfect for nature lovers seeking tranquility.",
    price: 399,
    image:
      "https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800&q=80",
    guests: 2,
    bed: "King bed",
    view: "Mountain view",
    sqft: 460,
    floor: "Ground Floor",
    roomNumber: "A04",
    highlights: [
      { icon: "wifi", label: "Premium WiFi" },
      { icon: "coffee", label: "Coffee maker" },
      { icon: "tv", label: '55" Smart TV' },
      { icon: "wind", label: "Smart climate" },
      { icon: "bathtub", label: "Soaking tub" },
      { icon: "bar", label: "Mini bar" },
    ],
  },
  {
    id: 8,
    name: "Skyline Penthouse",
    description: "Luxury living with floor-to-ceiling windows",
    fullDescription:
      "Ultra-modern penthouse with 360-degree city views, private elevator access, and rooftop entertainment area. The pinnacle of urban luxury.",
    price: 849,
    image:
      "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&q=80",
    guests: 3,
    bed: "King bed",
    view: "Skyline view",
    sqft: 800,
    floor: "Second Floor",
    roomNumber: "C02",
    highlights: [
      { icon: "wifi", label: "Premium WiFi" },
      { icon: "coffee", label: "Espresso machine" },
      { icon: "tv", label: '75" Smart TV' },
      { icon: "wind", label: "Smart climate" },
      { icon: "bathtub", label: "Luxury bath" },
      { icon: "bar", label: "Premium bar" },
    ],
  },
  {
    id: 9,
    name: "Royal Suite",
    description: "Regal elegance with antique furnishings and modern comfort",
    fullDescription:
      "Opulent suite blending classical elegance with modern luxury. Features hand-selected antique furnishings, marble bathroom, and private dining area.",
    price: 999,
    image:
      "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800&q=80",
    guests: 4,
    bed: "King bed",
    view: "Palace view",
    sqft: 950,
    floor: "First Floor",
    roomNumber: "B03",
    highlights: [
      { icon: "wifi", label: "Premium WiFi" },
      { icon: "coffee", label: "Espresso machine" },
      { icon: "tv", label: '75" Smart TV' },
      { icon: "wind", label: "Smart climate" },
      { icon: "bathtub", label: "Marble bath" },
      { icon: "bar", label: "Premium bar" },
    ],
  },
  {
    id: 10,
    name: "Sunset Villa",
    description: "Watch stunning sunsets from your private balcony",
    fullDescription:
      "West-facing villa with expansive balcony designed for sunset viewing. Includes outdoor lounge area and premium telescope for stargazing.",
    price: 599,
    image:
      "https://images.unsplash.com/photo-1568495248636-6432b97bd949?w=800&q=80",
    guests: 3,
    bed: "Queen bed",
    view: "Sunset view",
    sqft: 580,
    floor: "Ground Floor",
    roomNumber: "A05",
    highlights: [
      { icon: "wifi", label: "Premium WiFi" },
      { icon: "coffee", label: "Coffee maker" },
      { icon: "tv", label: '60" Smart TV' },
      { icon: "wind", label: "Smart climate" },
      { icon: "bathtub", label: "Soaking tub" },
      { icon: "bar", label: "Mini bar" },
    ],
  },
  {
    id: 11,
    name: "Spa Suite",
    description: "Wellness retreat with in-room spa facilities",
    fullDescription:
      "Ultimate wellness experience with in-room massage table, aromatherapy system, and private sauna. Includes complimentary daily spa treatments.",
    price: 499,
    image:
      "https://images.unsplash.com/photo-1615874959474-d609969a20ed?w=800&q=80",
    guests: 2,
    bed: "King bed",
    view: "Garden view",
    sqft: 510,
    floor: "Ground Floor",
    roomNumber: "A06",
    highlights: [
      { icon: "wifi", label: "Premium WiFi" },
      { icon: "coffee", label: "Herbal tea" },
      { icon: "tv", label: '55" Smart TV' },
      { icon: "wind", label: "Air purifier" },
      { icon: "bathtub", label: "Spa tub" },
      { icon: "bar", label: "Wellness bar" },
    ],
  },
  {
    id: 12,
    name: "Family Suite",
    description: "Spacious accommodations perfect for families",
    fullDescription:
      "Multi-room suite designed for families with separate children's area, entertainment system, and adjoining parent's bedroom. Kid-friendly amenities included.",
    price: 649,
    image:
      "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=800&q=80",
    guests: 5,
    bed: "2 King beds",
    view: "Resort view",
    sqft: 780,
    floor: "First Floor",
    roomNumber: "B04",
    highlights: [
      { icon: "wifi", label: "Premium WiFi" },
      { icon: "coffee", label: "Coffee maker" },
      { icon: "tv", label: '2x 55" TVs' },
      { icon: "wind", label: "Smart climate" },
      { icon: "bathtub", label: "Family bath" },
      { icon: "bar", label: "Snack bar" },
    ],
  },
];

// Get room by ID
export function getRoomById(id: number) {
  return roomsData.find((room) => room.id === id);
}
